function add_pid(mdl, Q_ss, Kp_m, Ki_m)

%master1
add_block('simulink/Math Operations/Sum', [mdl '/MasterErr1']);
set_param([mdl '/MasterErr1'], 'Inputs', '+-');

add_block('simulink/Continuous/PID Controller', [mdl '/MasterPI1']);
set_param([mdl '/MasterPI1'],                               ...
'Controller',                   'PI',                   ...
'P',                            num2str(Kp_m),          ...
'I',                            num2str(Ki_m),          ...
'AntiWindupMode',               'clamping',             ...
'InitialConditionForIntegrator',num2str(Q_ss),                    ...
'LimitOutput',                  'on',                   ...
'UpperSaturationLimit',         num2str(2 * Q_ss),      ...  % max Q12_ref
'LowerSaturationLimit',         '0');

add_line(mdl, 'h1/1',        'MasterErr1/1', 'autorouting', 'on'); % h1      → +
add_line(mdl, 'h1_ref/1',     'MasterErr1/2', 'autorouting', 'on'); % h_ref   → -
add_line(mdl, 'MasterErr1/1','MasterPI1/1',  'autorouting', 'on'); % error   → master PI
add_line(mdl, 'MasterPI1/1', 'SlaveErr1/1',  'autorouting', 'on'); % Q12_ref → +

%master2
add_block('simulink/Math Operations/Sum', [mdl '/MasterErr2']);
set_param([mdl '/MasterErr2'], 'Inputs', '+-');

add_block('simulink/Continuous/PID Controller', [mdl '/MasterPI2']);
set_param([mdl '/MasterPI2'],                                ...
'Controller',                   'PI',                    ...
'P',                            num2str(Kp_m),           ...
'I',                            num2str(Ki_m),           ...
'AntiWindupMode',               'clamping',              ...
'InitialConditionForIntegrator',num2str(Q_ss),           ...
'LimitOutput',                  'on',                    ...
'UpperSaturationLimit',         num2str(2 * Q_ss),       ...
'LowerSaturationLimit',         '0');

add_line(mdl, 'h2/1',        'MasterErr2/1', 'autorouting', 'on');
add_line(mdl, 'h2_ref/1',     'MasterErr2/2', 'autorouting', 'on');
add_line(mdl, 'MasterErr2/1','MasterPI2/1',  'autorouting', 'on');
add_line(mdl, 'MasterPI2/1', 'SlaveErr2/1',  'autorouting', 'on');
end
